import json
import os
import argparse

def main(input_log_path, output_log_path, db_id):
    dev_file_path = "db/bird-1/dev.json"

    if not os.path.exists(input_log_path) or not os.path.exists(dev_file_path):
        print("Error: Required files not found. Please check your paths.")
        return

    # Load the original benchmark dataset to extract the expected golden queries
    with open(dev_file_path, 'r', encoding='utf-8') as file:
        benchmark_data = json.load(file)

    golden_queries_map = {}
    for item in benchmark_data:
        if item.get("db_id") == db_id:
            golden_queries_map[item["question_id"]] = {
                "nl_query": item["question"],
                "golden_query": item["SQL"]
            }

    # Load the raw execution logs generated by the agent
    with open(input_log_path, 'r', encoding='utf-8') as file:
        execution_logs = json.load(file)

    simplified_logs = []

    # Merge the ground truth data with the actual agent results
    for log in execution_logs.get("detailed_queries", []):
        query_id = log.get("query_id")
        ground_truth = golden_queries_map.get(query_id, {})
        
        summary_entry = {
            "query_id": query_id,
            "nl_query": ground_truth.get("nl_query", "Not found"),
            "golden_query": ground_truth.get("golden_query", "Not found"),
            "generated_query": log.get("sparksql_query", "No SQL generated"),
            "execution_status": log.get("execution_status"),
            "spark_error": log.get("spark_error"),
            "query_result": log.get("query_result"),
            "accuracy": log.get("accuracy", "Not available")
        }
        simplified_logs.append(summary_entry)

    # Save the cleaned and simplified dataset to the specified output file
    with open(output_log_path, 'w', encoding='utf-8') as file:
        json.dump(simplified_logs, file, indent=4, ensure_ascii=False)

    print(f"Success! Created '{output_log_path}' containing {len(simplified_logs)} queries.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Simplify agent execution logs for easier analysis.")
    parser.add_argument("--input", type=str, required=True, help="Path to the raw input log file (e.g., logs/rag_toxicology.json)")
    parser.add_argument("--output", type=str, required=True, help="Path for the simplified output JSON (e.g., simplified_analysis_rag.json)")
    parser.add_argument("--db_id", type=str, required=True, help="Database ID to filter queries (e.g., toxicology)")

    args = parser.parse_args()
    main(args.input, args.output, args.db_id)